.\" Manpage for FreeMine.
.\" Contact anton2920@gmail.com for comments or help.
.TH man 1 "06 Apr 2019" "1.0" "FreeMine man page"
.SH NAME
FreeMine
.SH SYNOPSIS
FreeMine
.SH DESCRIPTION
FreeMine is a clone of the famous Microsoft Windows game.
.SH OPTIONS
FreeMine takes one (or less) argument to run with a specific game field size: 0 — small, 1 — medium, 2 — large.
.SH BUGS
No known bugs.
.SH AUTHOR
anton2920 (anton2920@gmail.com)
